name: firebase_sample
description: A new Flutter project.

publish_to: 'none'

version: 1.5.0+13

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  device_info: ^2.0.0

  # data store
  shared_preferences: ^2.0.5

  # get: ^3.1.1
  # Add the dependency for the Firebase Core Flutter SDK
  # firebase_auth: ^0.16.1
  # google_sign_in: ^4.5.1
  cupertino_icons: ^1.0.3

  # Architecture
  provider: ^5.0.0

  # File access
  path_provider: ^2.0.1

  # Image
  image_picker: ^0.7.4
  photo_view: ^0.11.1

  # File storage
  firebase_core: ^1.1.0
  firebase_storage: ^8.0.5
  cloud_firestore: 1.0.7
  firebase_messaging: ^9.1.3

  # circular check box
  circular_check_box: ^1.0.4

  # Date format
  intl: ^0.17.0

  # pull to refresh
  pull_to_refresh: ^2.0.0

  # Icon
  font_awesome_flutter: ^9.0.0

  # QR code generator
  qr_flutter: ^4.0.0

  # List Animation
  flutter_slidable: ^0.6.0

  # Date and time picker
  flutter_datetime_picker: ^1.5.1

  # アプリレビュー
  rate_my_app: ^1.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - languages/en.json
    - languages/ja.json