name: firebase_sample
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # get: ^3.1.1
  # Add the dependency for the Firebase Core Flutter SDK
  # firebase_auth: ^0.16.1
  # google_sign_in: ^4.5.1
  cupertino_icons: ^0.1.3

  # Architecture
  provider: ^4.3.2

  # ファイルアクセス関連
  path_provider: ^1.6.8

  # 画像取得
  image_picker: ^0.6.7+7

  # 動画表示
  video_player: ^1.0.1
  chewie:

  # ファイルストレージ
  firebase_core: ^0.4.5
  firebase_storage: ^3.0.3
  cloud_firestore: ^0.12.9+5

  # circular check box
  circular_check_box: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
