name: firebase_sample
description: A new Flutter project.

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  device_info: ^1.0.0

  # data store
  shared_preferences: ^0.5.6+2

  # get: ^3.1.1
  # Add the dependency for the Firebase Core Flutter SDK
  # firebase_auth: ^0.16.1
  # google_sign_in: ^4.5.1
  cupertino_icons: ^0.1.3

  # Architecture
  provider: ^4.3.2

  # File access
  path_provider: ^1.6.8

  # Image
  image_picker: ^0.6.7+7
  photo_view: ^0.10.2

  # Video player
  video_player: ^1.0.1
  chewie:

  # File storage
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  cloud_firestore: ^0.16.0

  # circular check box
  circular_check_box: ^1.0.4

  # Date format
  intl: ^0.16.1

  # pull to refresh
  pull_to_refresh: 1.6.3

  # Icon
  font_awesome_flutter: ^8.11.0

  # QR code generator
  qr_flutter: ^3.2.0

  # Dynamic Links
  firebase_dynamic_links: ^0.7.0+1

  # Firebase Messaging
  firebase_messaging: 6.0.16

  # List Animation
  flutter_slidable: ^0.5.7

  # Date and time picker
  flutter_datetime_picker: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - languages/en.json
    - languages/ja.json